### ISSUE TITLE
not working with docker-compose domain

### ISSUE THREAD

**Issue by realivanjx** [FlareSolverr/FlareSolverrSharp#10]
i have a docker-compose file like this:
```
    app-proxy:
        image: flaresolverr/flaresolverr:v2.2.4
        restart: always

    app:
        image: app:latest
        restart: always
        environment:
            FLARESOLVERR_ENDPOINT: "http://app-proxy:8191"
```

the above config does not work and keeps giving me invalid cookie error. the config below works just fine.

```
    app-proxy:
        image: flaresolverr/flaresolverr:v2.2.4
        restart: always
        ports:
            - 127.0.0.1:8191:8191/tcp

    app:
        image: app:latest
        restart: always
        network_mode: "host" # To access proxy.
        environment:
            FLARESOLVERR_ENDPOINT: "http://127.0.0.1:8191"
```

is it possible to make it work with the 1st config? thanks.
